### ISSUE TITLE
Unit test?

### ISSUE THREAD

**Issue by junaruga** [banister/debug_inspector#10]
Hello,

`debug_inspector` is a part of Rails.
and `debug_inspector` RPM package is manged by Fedora Project.
https://admin.fedoraproject.org/pkgdb/package/rpms/rubygem-debug_inspector/

So, I want to add unit tests to test `debug_inspector`.
And I guess that nowadays `minitest` is best choice for that.

Can you add the tests?
I am going to send pull-request as my proposal.

**Comment by junaruga** [comment]
Thanks.
If possible, I want to ask you to add "healthy code status" link to https://travis-ci.org/banister/debug_inspector to your `README.md` like `rails` https://github.com/rails/rails .

**Comment by junaruga** [comment]
Hello @banister 
Can you activate Travis CI?
https://travis-ci.org/banister/debug_inspector

**Comment by banister** [comment]
@junaruga i just added you as a collaborator to this repo, let me know if you're able to do what's necessary to get it setup as travis isn't something i've played with for a while now

**Comment by junaruga** [comment]
@banister thanks for adding me and enabling Travis CI! OK I will try to do it.
