### ISSUE TITLE
Adding license file

### ISSUE THREAD

**Issue by junaruga** [banister/debug_inspector#15]
I guess that it is recommended to add license file such as `LICENSE.txt` or `LICENSE.md` by github or generally rather than including it in `README.md`.
It is also recommended on Fedora Project (Linux OS project).

We can create it from github Web UI.
https://help.github.com/articles/adding-a-license-to-a-repository/

Here is a sample for that.
https://github.com/rspec/rspec-core

@banister I can work for that if you like.

**Comment by junaruga** [comment]
@banister how do you think?
It's like a removing license content from `README.md`, adding license file such as https://github.com/rails/rails .

**Comment by eregon** [comment]
Feel free to make a PR, however it seems already very clearly MIT (from README and gemspec)

**Comment by junaruga** [comment]
All right. I sent the PR https://github.com/banister/debug_inspector/pull/39.
