### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by walski** [banister/debug_inspector#27]
Hey, to make https://github.com/banister/binding_of_caller compatible with Ruby 3, we need to use a variant of this gem that support Ruby 3, too (e.g. `master` :) ).

Any chance someone can cut a new release and push it to rubygems.org? Thank you!!!

**Comment by RobinDaugherty** [comment]
This was waiting for #26, which has now been merged. Rubygems release should be coming soon.

**Comment by walski** [comment]
Thanks so much
