### ISSUE TITLE
debug_inspector.so cannot be found

### ISSUE THREAD

**Issue by ygpark2** [banister/debug_inspector#29]
`LoadError:` cannot load such file -- /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/debug_inspector-1.0.0/lib/debug_inspector.so

The latest upgrade seems to find wrong place of the "debug_inspector.so"

The "debug_inspector.so" file is located under the ext folder not lib folder.

https://github.com/banister/debug_inspector/blob/7bb09517282a41b3fdf3c204f46acebf17896b51/lib/debug_inspector.rb#L4

I think this line should refer to the ext folder.

Please have a look at this issue.

**Comment by RobinDaugherty** [comment]
@ygpark2 can you please try debug_inspector 1.1.0rc1? It should fix your issue.

**Comment by ygpark2** [comment]
Yep

It seems to work.

Thank you!
