### ISSUE TITLE
JRuby

### ISSUE THREAD

**Issue by Integralist** [banister/debug_inspector#4]
Hi,

This might very well be a redundant question: is there any chance this port can be made to work without the underlining C implementation?

e.g. I want to utilise it within a JRuby application and although I can temporarily enable C extension support; that will option will be removed in future releases.

Just curious if a non-C variation existed?

**Comment by eregon** [comment]
This would need to be contributed and finding out if such an API exists in JRuby.

**Comment by eregon** [comment]
I'll close this as not planned.
