### ISSUE TITLE
License missing in gemspec

### ISSUE THREAD

**Issue by strzibny** [banister/debug_inspector#5]
Please include licensing info to gemspec as well. Thanks.

**Comment by kerrizor** [comment]
License was add in #7

**Comment by kerrizor** [comment]
..I will note though that the license was added to `0.0.2` but a new release will need to be cut and pushed to RubyGems for your local version to pick up the change.

@banister would you accept a small PR for that? Would clean up my auditing code.. <3

**Comment by banister** [comment]
@kerrizor sure thing :)

**Comment by junaruga** [comment]
We would close this ticket because https://github.com/banister/debug_inspector/pull/13 was merged, and new version `0.0.3` was released.
